# Generated by Django 4.1 on 2023-12-04 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(editable=False, max_length=32)),
                ("full_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=40)),
                ("postcode", models.CharField(blank=True, max_length=20)),
                ("town_or_city", models.CharField(max_length=40)),
                ("street_address1", models.CharField(max_length=80)),
                ("street_address2", models.CharField(blank=True, max_length=80)),
                ("county", models.CharField(blank=True, max_length=80)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "order_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "lineitem_total",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=6),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineitems",
                        to="checkout.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
