# Generated by Django 4.1 on 2023-12-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
