# Generated by Django 4.1 on 2023-12-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0002_order_delivery_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="original_bag",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="stripe_pid",
            field=models.CharField(default="", max_length=254),
        ),
    ]
