# Generated by Django 4.1 on 2024-01-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="superuser_read",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="messages",
            name="user_read",
            field=models.BooleanField(default=True),
        ),
    ]
