# Generated by Django 4.1 on 2024-01-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="last_message",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
