# Generated by Django 4.1 on 2024-01-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_system", "0002_messages_last_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="last_message_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
