# Generated by Django 4.2.6 on 2023-10-29 22:22

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[400, None], upload_to='products/')),
                ('image_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shoe_size', models.CharField(choices=[(2, '2'), (2.5, '2.5'), (3, '3'), (3.5, '3.5'), (4, '4'), (4.5, '4.5'), (5, '5'), (5.5, '5.5'), (6, '6'), (6.5, '6.5'), (7, '7'), (7.5, '7.5'), (8, '8'), (8.5, '8.5'), (9, '9'), (9.5, '9.5'), (10, '10'), (10.5, '10.5'), (11, '11'), (11.5, '11.5'), (12, '12'), (12.5, '12.5'), (13, '13'), (13.5, '13.5'), (14, '14'), (14.5, '14.5')], default='8', max_length=10)),
                ('shoe_sex', models.CharField(max_length=10)),
                ('shoe_type', models.CharField(choices=[('sneakers', 'Sneakers'), ('sandals', 'Sandals'), ('boots', 'Boots'), ('flats', 'Flats'), ('high_heels', 'High Heels'), ('loafers', 'Loafers'), ('running_shoes', 'Running Shoes'), ('basketball_shoes', 'Basketball Shoes'), ('tennis_shoes', 'Tennis Shoes'), ('hiking_boots', 'Hiking Boots'), ('rain_boots', 'Rain Boots'), ('ankle_boots', 'Ankle Boots'), ('platform_shoes', 'Platform Shoes'), ('mules', 'Mules'), ('chukka_boots', 'Chukka Boots'), ('cowboy_boots', 'Cowboy Boots')], default='Sneakers', max_length=50)),
                ('shoe_brand', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
