# Generated by Django 4.1 on 2023-11-12 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_url',
            new_name='file_url',
        ),
    ]
