# Generated by Django 4.2.6 on 2023-10-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shoe_brand',
            field=models.CharField(choices=[('nike', 'Nike'), ('adidas', 'Adidas'), ('puma', 'Puma'), ('reebok', 'Reebok'), ('converse', 'Converse'), ('new_balance', 'New Balance'), ('vans', 'Vans'), ('under_armour', 'Under Armour'), ('skechers', 'Skechers'), ('asics', 'ASICS'), ('brooks', 'Brooks'), ('clarks', 'Clarks'), ('timberland', 'Timberland'), ('dr_martens', 'Dr. Martens'), ('fila', 'FILA'), ('merrell', 'Merrell'), ('salomon', 'Salomon'), ('ecco', 'Ecco'), ('lacoste', 'Lacoste'), ('saucony', 'Saucony'), ('vionic', 'Vionic'), ('mizuno', 'Mizuno'), ('hoka_one_one', 'Hoka One One'), ('under_armour', 'Under Armour'), ('skechers', 'Skechers'), ('birkenstock', 'Birkenstock'), ('ugg', 'UGG'), ('cole_haan', 'Cole Haan'), ('steve_madden', 'Steve Madden'), ('aldo', 'Aldo'), ('fendi', 'Fendi'), ('gucci', 'Gucci'), ('prada', 'Prada'), ('versace', 'Versace'), ('balenciaga', 'Balenciaga'), ('louis_vuitton', 'Louis Vuitton'), ('jimmy_choo', 'Jimmy Choo'), ('christian_louboutin', 'Christian Louboutin'), ('valentino', 'Valentino'), ('dior', 'Dior')], default='Nike', max_length=50),
        ),
    ]
