# Generated by Django 4.1 on 2024-01-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="image_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
