# Generated by Django 4.1 on 2024-01-13 18:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_productimage_image_url"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductImage",
            new_name="Image",
        ),
    ]
