# Generated by Django 4.1 on 2023-11-08 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_brand_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='shoe_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='shoe_type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='shoe_size',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_alt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
