# Generated by Django 4.1 on 2023-11-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_size_rename_brands_brand_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shoe_sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Female', max_length=50),
        ),
    ]
