# Generated by Django 4.1 on 2024-01-13 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_product_banner_alter_productimage_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="banner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="banner",
                to="products.productimage",
            ),
        ),
    ]
