# Generated by Django 4.1 on 2024-01-13 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_alter_product_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="banner",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="banner",
                to="products.productimage",
            ),
        ),
    ]
